<a href="https://colab.research.google.com/github/AlijaNoushad/Alija-assignments-casestudy/blob/main/preprocessingassignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = pd.read_csv('/content/titanic_dataset.csv')

data.set_index('PassengerId', inplace=True)
print("Data with 'PassengerId' as index:\n", data.head())

print("\nData Information:\n")
print(data.info())
print("\nSummary Statistics:\n", data.describe())

for column in data.columns:
    if data[column].dtype == 'object':
        data[column].fillna(data[column].mode()[0], inplace=True)
    else:
        data[column].fillna(data[column].median(), inplace=True)
print("\nData after filling missing values:\n", data.head())

def cap_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])
    return df

columns_to_cap = ['Age', 'Fare', 'SibSp']
for column in columns_to_cap:
    data = cap_outliers(data, column)
print("\nData after handling outliers:\n", data[columns_to_cap].head())

scaler = MinMaxScaler()
features = data.drop('Survived', axis=1)
target = data['Survived']
features_scaled = pd.DataFrame(scaler.fit_transform(features_to_scale),columns=features_to_scale.columns,index=features.index)
print("\nScaled Features:\n", features_scaled.head())

Data with 'PassengerId' as index:
              Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3

                                                          Name     Sex   Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
5                                     Allen, Mr. William Henry    male  35.0

             SibSp  Parch            Ticket     Fare Cabin Embarked
PassengerId
1                1      0         A/5 21171   7.2500   NaN        S
2                1      0          PC 17599  71.2833   C85        C
3                0      0  STON/O2. 3101282   7.9250   NaN        S
4                1      0            113803  53.1000  C123        S
5                0      0            373450   8.0500   NaN        S

Data Information:

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB
None

Summary Statistics:
          Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Data after filling missing values:
              Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3

                                                          Name     Sex   Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
5                                     Allen, Mr. William Henry    male  35.0

             SibSp  Parch            Ticket     Fare    Cabin Embarked
PassengerId
1                1      0         A/5 21171   7.2500  B96 B98        S
2                1      0          PC 17599  71.2833      C85        C
3                0      0  STON/O2. 3101282   7.9250  B96 B98        S
4                1      0            113803  53.1000     C123        S
5                0      0            373450   8.0500  B96 B98        S

Data after handling outliers:
               Age     Fare  SibSp
PassengerId
1            22.0   7.2500    1.0
2            38.0  65.6344    1.0
3            26.0   7.9250    0.0
4            35.0  53.1000    1.0
5            35.0   8.0500    0.0

Scaled Features:
              Pclass       Age  SibSp  Parch      Fare
PassengerId
1               1.0  0.375000    0.4    0.0  0.110460
2               0.0  0.682692    0.4    0.0  1.000000
3               1.0  0.451923    0.0    0.0  0.120745
4               0.0  0.625000    0.4    0.0  0.809027
5               1.0  0.625000    0.0    0.0  0.122649

<ipython-input-11-fb73a754b354>:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(data[column].median(), inplace=True)
<ipython-input-11-fb73a754b354>:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(data[column].mode()[0], inplace=True)